### ISSUE TITLE
Broken pipe: Due to empty r2pipe open call

### ISSUE THREAD

**Issue by vineetpurswani** [kamou/pimp#1]
I do understand that plugin's pipe should interact with the current r2 process. But that isn't happening. What should I do?

PS: I have installed radare2 from its git repo, all of it.

**Comment by vineetpurswani** [comment]
Adding traceback,

```
Missing file to open
Traceback (most recent call last):
  File "/home/fachika/repos/pimp/pimp.py", line 389, in <module>
    pimp = Pimp()
  File "/home/fachika/repos/pimp/pimp.py", line 117, in __init__
    self.r2p = R2("pimp")
  File "/home/fachika/repos/pimp/pimp.py", line 14, in __init__
    bininfo = self.r2.cmdj("ij")["bin"]
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/__init__.py", line 225, in cmdj
    data = json.loads(self.cmd(cmd))
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/__init__.py", line 215, in cmd
    return self._cmd(cmd)
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/__init__.py", line 145, in _cmd_process
    self.process.stdin.write(cmd+'\n')
IOError: [Errno 32] Broken pipe
```

**Comment by kamou** [comment]
how are you running the script ?
and are you using r2pipe from git as well ?

**Comment by kamou** [comment]
ping !

**Comment by kamou** [comment]
All you need for pimp to work properly is:
Update your r2pipe radare2 packages to the latest git versions..
Install lang-python2 from r2pm.
Make sure r2 and Triton are compiled against the same capstone version.

This is not a pimp issue.
